# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b8c4c31155f89cab2ff8b0c680e607d061781e3fbf00ce10b7c2f54383e6b2c10b12f0baa58f50d31629bcdbb9ccd1e155112cd31d28ef3fd50a431a8b10d38

test:
  secret_key_base: 869761b50d570bafd321a760ca37d8129b5cff7f43b4e9cd81c9ebc89a76f41428074516d3fc427dd559c5c97c38b11d22689b559996acc467afd50df6491073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
